import turtle
t = turtle.Turtle()
t.shape("turtle")
t.fd(100)
name = turtle.textinput("제목입력칸 ","이름을 입력하세요.")
t.write("안녕하세요? "+name+"인데요")
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
